package com.example.ott.sott.utils.enums

enum class RailTypes {
    CAROUSEL_LDS_LANDSCAPE,
    HORIZONTAL_LDS_LANDSCAPE,
    HORIZONTAL_CIR_CIRCLE,
    HORIZONTAL_CIR_CIRCLE_TRANSPARENT,
    HORIZONTAL_SQR_SQUARE,
    HORIZONTAL_SQR_SQUARE_TRANSPARENT,
    HORIZONTAL_PR_POTRAIT_9x16,
    HORIZONTAL_PR_POSTER,
    HORIZONTAL_PR_POTRAIT,
    HERO_LDS_BANNER
}
